version: "3.4"

services:
  app:
    image: learning-docker/node-app:v1
    hostname: nodeapp
    networks:
      - test-net
    volumes:
      - ./node-app:/app
    environment:
      - DB_HOST=${DB_HOST}  
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    restart: unless-stopped
    depends_on:
        - db  
  db:
    image: mongo
    networks:
      - test-net
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx/
    depends_on:
      - app
    networks:
      - test-net
    ports:
      - "4000:4000"
volumes:    
  mongodata:
networks:
  test-net:
    driver: bridge
    name: nodeapp-network

